from enum import Enum


class CaseStatus(str, Enum):
    OPEN = "OPEN"
    LOCKED = "LOCKED"
    ARCHIVED = "ARCHIVED"
    CLOSED = "CLOSED"


class EvidenceState(str, Enum):
    REGISTERED = "REGISTERED"
    COPYING = "COPYING"
    VERIFIED = "VERIFIED"
    HASH_MISMATCH = "HASH_MISMATCH"
    QUARANTINED = "QUARANTINED"
    UNSUPPORTED = "UNSUPPORTED"
    PARSED = "PARSED"
    PARTIALLY_PARSED = "PARTIALLY_PARSED"
    FAILED = "FAILED"


class ArtefactOrigin(str, Enum):
    PARSED = "PARSED"
    RECOVERED = "RECOVERED"
    INFERRED = "INFERRED"
    MANUAL = "MANUAL"
    IMPORTED = "IMPORTED"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNRESOLVED = "UNRESOLVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ValidationStatus(str, Enum):
    VALIDATED = "VALIDATED"
    PARTIAL = "PARTIAL"
    UNVERIFIED = "UNVERIFIED"
    REJECTED = "REJECTED"
    UNSUPPORTED = "UNSUPPORTED"


class MessageDirection(str, Enum):
    INCOMING = "INCOMING"
    OUTGOING = "OUTGOING"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"


class MessageType(str, Enum):
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"
    VOICE_NOTE = "VOICE_NOTE"
    DOCUMENT = "DOCUMENT"
    STICKER = "STICKER"
    GIF = "GIF"
    LOCATION = "LOCATION"
    LIVE_LOCATION = "LIVE_LOCATION"
    CONTACT = "CONTACT"
    POLL = "POLL"
    CALL_EVENT = "CALL_EVENT"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"


class CallType(str, Enum):
    VOICE = "VOICE"
    VIDEO = "VIDEO"
    GROUP_VOICE = "GROUP_VOICE"
    GROUP_VIDEO = "GROUP_VIDEO"
    UNKNOWN = "UNKNOWN"


class CallDirection(str, Enum):
    INCOMING = "INCOMING"
    OUTGOING = "OUTGOING"
    MISSED = "MISSED"
    DECLINED = "DECLINED"
    UNKNOWN = "UNKNOWN"


class EndpointClassification(str, Enum):
    PROBABLE_PEER = "PROBABLE_PEER"
    WHATSAPP_RELAY = "WHATSAPP_RELAY"
    TURN_SERVER = "TURN_SERVER"
    CLOUD_INFRASTRUCTURE = "CLOUD_INFRASTRUCTURE"
    MOBILE_CARRIER_GATEWAY = "MOBILE_CARRIER_GATEWAY"
    VPN_OR_PROXY = "VPN_OR_PROXY"
    LOCAL_GATEWAY = "LOCAL_GATEWAY"
    UNKNOWN = "UNKNOWN"


class ConversationType(str, Enum):
    DIRECT = "DIRECT"
    GROUP = "GROUP"
    BROADCAST = "BROADCAST"
    UNKNOWN = "UNKNOWN"


class SourceType(str, Enum):
    WHATSAPP_TEXT_EXPORT = "WHATSAPP_TEXT_EXPORT"
    WHATSAPP_EXPORT_ZIP = "WHATSAPP_EXPORT_ZIP"
    SQLITE_DATABASE = "SQLITE_DATABASE"
    SQLITE_DATABASE_PACKAGE = "SQLITE_DATABASE_PACKAGE"
    MEDIA_DIRECTORY = "MEDIA_DIRECTORY"
    DESKTOP_ARTIFACTS = "DESKTOP_ARTIFACTS"
    DECRYPTED_BACKUP = "DECRYPTED_BACKUP"
    PCAP = "PCAP"
    PCAPNG = "PCAPNG"
    THIRD_PARTY_FORENSIC_EXPORT = "THIRD_PARTY_FORENSIC_EXPORT"
    GENERIC_FILES = "GENERIC_FILES"


class AcquisitionMethod(str, Enum):
    USER_EXPORT = "USER_EXPORT"
    LOGICAL = "LOGICAL"
    FILESYSTEM = "FILESYSTEM"
    PHYSICAL = "PHYSICAL"
    DESKTOP_SNAPSHOT = "DESKTOP_SNAPSHOT"
    THIRD_PARTY_TOOL = "THIRD_PARTY_TOOL"
    NETWORK_CAPTURE = "NETWORK_CAPTURE"
    OTHER_AUTHORISED = "OTHER_AUTHORISED"


class RecoveryStrategy(str, Enum):
    WAL_PARSING = "WAL_PARSING"
    ROLLBACK_JOURNAL = "ROLLBACK_JOURNAL"
    FREELIST_SCAN = "FREELIST_SCAN"
    UNALLOCATED_CARVING = "UNALLOCATED_CARVING"
    ORPHAN_MEDIA = "ORPHAN_MEDIA"
    THUMBNAIL_CORRELATION = "THUMBNAIL_CORRELATION"
    DESKTOP_MOBILE_COMPARISON = "DESKTOP_MOBILE_COMPARISON"


class ReviewStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    UNRESOLVED = "UNRESOLVED"


class ParserRunStatus(str, Enum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    UNSUPPORTED = "UNSUPPORTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class RecoveryRunStatus(str, Enum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class CaptureMode(str, Enum):
    LIVE_PASSIVE = "LIVE_PASSIVE"
    PCAP_IMPORT = "PCAP_IMPORT"


class HashAlgorithm(str, Enum):
    SHA256 = "SHA256"
    SHA512 = "SHA512"
    MD5 = "MD5"


class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class FileState(str, Enum):
    CREATING = "CREATING"
    READY = "READY"
    IN_USE = "IN_USE"
    FAILED = "FAILED"
    DELETED = "DELETED"
